\rm -rf genesis.log;
\rm -rf genesis_work;
\rm -rf genesis_raw;
\rm -rf genesis_verif;
\rm -rf genesis_synth;
\rm -f top.xml small_top.xml tiny_top.xml;
\rm -f genesis_vlog.vf;
\rm -f genesis_vlog.synth.vf;
\rm -f genesis_vlog.verif.vf;
\rm -f genesis_clean.cmd;
