//
//--------------------------------------------------------------------------------
//          THIS FILE WAS AUTOMATICALLY GENERATED BY THE GENESIS2 ENGINE        
//  FOR MORE INFORMATION: OFER SHACHAM (CHIP GENESIS INC / STANFORD VLSI GROUP)
//    !! THIS VERSION OF GENESIS2 IS NOT FOR ANY COMMERCIAL USE !!
//     FOR COMMERCIAL LICENSE CONTACT SHACHAM@ALUMNI.STANFORD.EDU
//--------------------------------------------------------------------------------
//
//  
//	-----------------------------------------------
//	|            Genesis Release Info             |
//	|  $Change: 11789 $ --- $Date: 2013/03/25 $   |
//	-----------------------------------------------
//	
//
//  Source file: /nobackup/nikhil3/github/CGRAGenerator/hardware/generator_z/memory_core/mem.vp
//  Source template: mem
//
// --------------- Begin Pre-Generation Parameters Status Report ---------------
//
//	From 'generate' statement (priority=5):
// Parameter dwidth 	= 16
// Parameter awidth 	= 9
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Command Line input (priority=4):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From XML input (priority=3):
//
//		---- ---- ---- ---- ---- ---- ---- ---- ---- ---- ----
//
//	From Config File input (priority=2):
//
// ---------------- End Pre-Generation Pramameters Status Report ----------------

///////////////////////////////////////////////////////////////////
// CGRA Memory generator 
/////////////////////////////////////////////////////////////////
// dwidth (_GENESIS2_INHERITANCE_PRIORITY_) = 16
//
// awidth (_GENESIS2_INHERITANCE_PRIORITY_) = 9
//

module mem_unq1 (
data_out, data_in,clk,cen,wen,addr
);

output [15:0] data_out;
input [15:0] data_in;
input clk;
input cen;
input wen;
input [8:0] addr;

wire clk_d;

assign #0.1 clk_d = clk;

sram_512w_16b mem_inst(
.Q(data_out), 
.CLK(clk),
.CEN(~cen), 
.WEN(~wen), 
.A(addr), 
.D(data_in), 
.EMA(3'd0), 
.EMAW(2'd0), 
.EMAS(1'b0), 
.TEN(1'b1),
.BEN(1'b1),
.RET1N(1'b1),
.STOV(1'b0));

endmodule
